<a href="https://colab.research.google.com/github/Tashin2025/Data_Science_W1/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Task 1

In [ ]:
arr = np.array([[5, 5],
                    [7, 7]])
print(arr)


[[5 5]
 [7 7]]


Task 2

In [ ]:
arr2 = np.random.rand(3, 4)
print(arr2)


[[0.57021183 0.68701612 0.37913113 0.65291385]
 [0.31216968 0.18266885 0.41406246 0.99350367]
 [0.0972342  0.02068389 0.20336962 0.78718735]]


Task 3

In [ ]:
ones_arr = np.ones((3, 3))
zeros_arr = np.zeros((3, 3))

print("Array of Ones:\n", ones_arr)
print("\n\nArray of Zeroes:\n", zeros_arr)


Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Array of Zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Task4

In [ ]:
arr_6x3 = np.random.rand(6, 3)
print("Original Array:\n", arr_6x3)
print("Transposed:\n", arr_6x3.T)


Original Array:
 [[0.70523253 0.29260889 0.48131553]
 [0.99734803 0.0046157  0.09178516]
 [0.34108948 0.44945656 0.17958227]
 [0.07056838 0.52007065 0.65045052]
 [0.53229774 0.65957059 0.97874901]
 [0.85355791 0.5446467  0.67108702]]
Transposed:
 [[0.70523253 0.99734803 0.34108948 0.07056838 0.53229774 0.85355791]
 [0.29260889 0.0046157  0.44945656 0.52007065 0.65957059 0.5446467 ]
 [0.48131553 0.09178516 0.17958227 0.65045052 0.97874901 0.67108702]]


Task 5

In [ ]:
n, p, m = 3, 2, 4

A = np.random.rand(n, p)
B = np.random.rand(p, m)

dot_product = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Dot Product (A × B):\n", dot_product)


Matrix A:
 [[0.60894633 0.78847413]
 [0.02780284 0.0224129 ]
 [0.79064756 0.06825938]]
Matrix B:
 [[0.55789198 0.02212107 0.66427123 0.94071859]
 [0.4812198  0.4658049  0.01565896 0.01949708]]
Dot Product (A × B):
 [[0.71915564 0.38074566 0.41685221 0.58822008]
 [0.02629651 0.01105507 0.01881959 0.02659163]
 [0.4739437  0.04928553 0.52627329 0.74510772]]
